# Generated by Django 5.2.8 on 2025-11-15 07:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('MAYORISTA', 'Mayorista'), ('MINORISTA', 'Minorista')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Localidades',
            },
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('MOTO', 'Moto'), ('CAMIONETA', 'Camioneta'), ('CAMION', 'Camión')], max_length=20)),
                ('capacidad_kg', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Vehículos',
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('EN_CAMINO', 'En Camino'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('peso_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direccion_entrega', models.CharField(max_length=255)),
                ('lat_entrega', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('lng_entrega', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('localidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BACKEND.localidades')),
                ('mayorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_mayorista', to='BACKEND.empresas')),
                ('minorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_minorista', to='BACKEND.empresas')),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Envios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ASIGNADO', 'Asignado'), ('EN_RUTA', 'En Ruta'), ('ENTREGADO', 'Entregado'), ('FALLIDO', 'Fallido')], default='ASIGNADO', max_length=20)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BACKEND.pedidos')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BACKEND.vehiculos')),
            ],
            options={
                'verbose_name_plural': 'Envíos',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('altura_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ancho_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('largo_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BACKEND.empresas')),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='RastreoEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=10)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BACKEND.envios')),
            ],
            options={
                'verbose_name_plural': 'Rastreo de Envíos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('MAYORISTA', 'Mayorista'), ('MINORISTA', 'Minorista'), ('CONDUCTOR', 'Conductor'), ('ADMIN', 'Administrador')], default='MINORISTA', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('disponibilidad', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_RUTA', 'En Ruta'), ('DESCANSO', 'Descanso')], default='DISPONIBLE', max_length=20)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='conductor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculo_asignado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='envios',
            name='conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_conducidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresas',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Asignaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('criterio', models.CharField(choices=[('MAS_CERCANO', 'Más Cercano'), ('MAYOR_CAPACIDAD', 'Mayor Capacidad'), ('MENOS_CARGA', 'Menos Carga'), ('ALGORITMO_MIXTO', 'Algoritmo Mixto')], max_length=50)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BACKEND.pedidos')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BACKEND.vehiculos')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_conductor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Asignaciones',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BACKEND.pedidos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BACKEND.productos')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Pedido',
                'unique_together': {('pedido', 'producto')},
            },
        ),
        migrations.CreateModel(
            name='ConductoresZonas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BACKEND.localidades')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Zonas de Conductores',
                'unique_together': {('conductor', 'localidad')},
            },
        ),
    ]
