# Generated by Django 5.2.8 on 2025-12-01 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BACKEND', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos',
            old_name='fecha_pedido',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='direccion_entrega',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='lat_entrega',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='lng_entrega',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='mayorista',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='peso_total',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='conductor',
            field=models.ForeignKey(blank=True, help_text='Conductor asignado al pedido.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='destino',
            field=models.CharField(default='Dirección no registrada', help_text='Dirección de entrega.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidos',
            name='origen',
            field=models.CharField(default='Origen no registrado', help_text='Dirección de recolección.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidos',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Peso total de la carga en kg.', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidos',
            name='tipo_carga',
            field=models.CharField(default='Sin descripción de carga', help_text='Descripción o dimensiones de la carga.', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asignaciones',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_asociada', to='BACKEND.pedidos'),
        ),
        migrations.AlterField(
            model_name='asignaciones',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_vehiculo', to='BACKEND.vehiculos'),
        ),
        migrations.AlterField(
            model_name='conductoreszonas',
            name='conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conductoreszonas',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conductores_asignados', to='BACKEND.localidades'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='BACKEND.pedidos'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_en_pedidos', to='BACKEND.productos'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_asociadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='envios',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envio_asociado', to='BACKEND.pedidos'),
        ),
        migrations.AlterField(
            model_name='envios',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_por_vehiculo', to='BACKEND.vehiculos'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADO', 'Asignado'), ('EN_TRANSITO', 'En Tránsito'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='minorista',
            field=models.ForeignKey(help_text='Usuario minorista que solicita la carga.', on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productos',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_ofrecidos', to='BACKEND.empresas'),
        ),
        migrations.AlterField(
            model_name='rastreoenvio',
            name='envio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_rastreo', to='BACKEND.envios'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='custom_user_groups', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
