# Generated by Django 5.2.8 on 2025-12-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BACKEND', '0002_rename_fecha_pedido_pedidos_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='tipo',
            field=models.CharField(choices=[('MINORISTA', 'Minorista'), ('CONDUCTOR', 'Conductor'), ('ADMIN', 'Administrador')], default='MINORISTA', max_length=20),
        ),
    ]
