# Generated by Django 5.2.8 on 2025-12-03 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BACKEND', '0003_alter_usuarios_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignaciones',
            options={'ordering': ['-fecha_asignacion'], 'verbose_name_plural': 'Asignaciones'},
        ),
        migrations.AlterModelOptions(
            name='rastreoenvio',
            options={'ordering': ['fecha_hora'], 'verbose_name_plural': 'Rastreo de Envíos'},
        ),
        migrations.RenameField(
            model_name='rastreoenvio',
            old_name='fecha',
            new_name='fecha_hora',
        ),
        migrations.RemoveField(
            model_name='asignaciones',
            name='criterio',
        ),
        migrations.RemoveField(
            model_name='asignaciones',
            name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='tipo_carga',
        ),
        migrations.RemoveField(
            model_name='rastreoenvio',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='rastreoenvio',
            name='lng',
        ),
        migrations.AddField(
            model_name='asignaciones',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Asignación Pendiente'), ('ACEPTADA', 'Asignación Aceptada por Conductor'), ('RECHAZADA', 'Asignación Rechazada por Conductor')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='descripcion_carga',
            field=models.CharField(default='Carga no especificada', help_text='Descripción general de la carga (ej: tipo, bultos).', max_length=100),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='peso_total_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Peso total estimado de la carga en kg.', max_digits=10),
        ),
        migrations.AddField(
            model_name='rastreoenvio',
            name='estado',
            field=models.CharField(choices=[('RECOLECCIÓN', 'Recolección Iniciada'), ('EN_CAMINO', 'En Camino al Destino'), ('EN_ENTREGA', 'Intentando Entrega'), ('COMPLETADO', 'Entregado Exitosamente')], default='RECOLECCIÓN', max_length=30),
        ),
        migrations.AddField(
            model_name='rastreoenvio',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rastreoenvio',
            name='ubicacion',
            field=models.CharField(default='Ubicación no registrada', help_text='Ciudad o dirección actual.', max_length=255),
        ),
        migrations.AlterField(
            model_name='asignaciones',
            name='conductor',
            field=models.ForeignKey(limit_choices_to={'tipo': 'CONDUCTOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asignaciones',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_asignaciones', to='BACKEND.pedidos'),
        ),
        migrations.AlterField(
            model_name='envios',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_conducidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='envios',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='envio_asociado', to='BACKEND.pedidos'),
        ),
        migrations.AlterField(
            model_name='envios',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_por_vehiculo', to='BACKEND.vehiculos'),
        ),
        migrations.AlterField(
            model_name='rastreoenvio',
            name='envio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rastreos', to='BACKEND.envios'),
        ),
    ]
