# Generated by Django 5.0 on 2025-12-16 06:03

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('MAYORISTA', 'Mayorista'), ('MINORISTA', 'Minorista')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placas_asignadas', models.CharField(blank=True, max_length=10, null=True)),
                ('marca_asignada', models.CharField(blank=True, max_length=50, null=True)),
                ('referencia_asignada', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_vehiculo_asignado', models.CharField(blank=True, choices=[('CAMIONETA', 'Camioneta'), ('FURGON', 'Furgón'), ('CAMION_PEQUEÑO', 'Camión Pequeño'), ('CAMION_GRANDE', 'Camión Grande'), ('MOTO', 'Motocicleta')], max_length=20, null=True)),
                ('tipo_mercancia', models.CharField(choices=[('PERECEDEROS', 'Perecederos'), ('REFRIGERADOS', 'Refrigerados'), ('CONTROLADOS', 'Controlados (Químicos, Medicamentos)'), ('PELIGROSOS', 'Mercancías Peligrosas'), ('FRAGIL', 'Frágil (Vidrio, Cerámica)'), ('VOLUMINOSO', 'Voluminoso'), ('PESADO', 'Pesado'), ('SECAS', 'Carga Seca General'), ('BEBIDAS', 'Bebidas'), ('EMPAQUETADOS', 'Empaquetados'), ('ALIMENTOS_PROCESADOS', 'Alimentos Procesados'), ('ELECTRONICOS', 'Electrónicos'), ('REPUESTOS', 'Repuestos'), ('MUEBLES', 'Muebles'), ('DECORACION', 'Decoración'), ('TEXTIL', 'Textil'), ('ROPA', 'Ropa'), ('PRENDAS', 'Prendas'), ('FARMACEUTICOS', 'Farmacéuticos'), ('HERRAMIENTAS', 'Herramientas'), ('MATERIALES', 'Materiales'), ('VIDRIO', 'Vidrio'), ('PLASTICOS', 'Plásticos'), ('ENVASES', 'Envases'), ('BATERIAS', 'Baterías'), ('CONGELADOS', 'Congelados'), ('GRANEL', 'Granel'), ('PAPEL', 'Papel'), ('CARTON', 'Cartón'), ('QUIMICOS', 'Químicos'), ('LIQUIDOS', 'Líquidos'), ('DEPORTIVO', 'Deportivo')], max_length=50)),
                ('peso_total', models.DecimalField(decimal_places=2, help_text='Peso en Kg', max_digits=10)),
                ('volumen', models.DecimalField(decimal_places=2, help_text='Volumen en m³', max_digits=10)),
                ('valor_declarado', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('unidades', models.PositiveIntegerField(default=1)),
                ('largo', models.DecimalField(decimal_places=2, default=0.1, help_text='Largo de la unidad (metros)', max_digits=5)),
                ('alto', models.DecimalField(decimal_places=2, default=0.1, help_text='Alto de la unidad (metros)', max_digits=5)),
                ('ancho', models.DecimalField(decimal_places=2, default=0.1, help_text='Ancho de la unidad (metros)', max_digits=5)),
                ('empresa_mayorista', models.CharField(blank=True, help_text='Clave del mayorista seleccionada', max_length=50, null=True)),
                ('origen', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('fecha_recoleccion', models.DateField()),
                ('hora_recoleccion', models.TimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADO', 'Asignado'), ('EN_RUTA', 'En Ruta'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('precio_estimado', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10)),
            ],
            options={
                'verbose_name': 'Pedido/Orden',
                'verbose_name_plural': 'Pedidos/Ordenes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=0, max_digits=10)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de Pago'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida'), ('ANULADA', 'Anulada')], default='PENDIENTE_PAGO', max_length=50)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='FRONTEND.pedidos')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='Envios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ASIGNADO', 'Asignado'), ('EN_RUTA', 'En Ruta'), ('ENTREGADO', 'Entregado'), ('FALLIDO', 'Fallido')], default='ASIGNADO', max_length=20)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='envio', to='FRONTEND.pedidos')),
            ],
            options={
                'verbose_name_plural': 'Envios',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('altura_cm', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ancho_cm', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('largo_cm', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FRONTEND.empresas')),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='RastreoEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=255)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rastreos', to='FRONTEND.envios')),
            ],
            options={
                'verbose_name_plural': 'Rastreo de Envíos',
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('tipo', models.CharField(choices=[('ADMIN', 'Administrador'), ('MINORISTA', 'Minorista'), ('CONDUCTOR', 'Conductor')], default='MINORISTA', max_length=10)),
                ('placas', models.CharField(blank=True, help_text='Placa del vehículo de transporte.', max_length=10, null=True)),
                ('marca_vehiculo', models.CharField(blank=True, help_text='Marca del vehículo.', max_length=50, null=True)),
                ('referencia_vehiculo', models.CharField(blank=True, help_text='Referencia/Modelo del vehículo.', max_length=50, null=True)),
                ('tipo_vehiculo', models.CharField(blank=True, choices=[('CAMIONETA', 'Camioneta'), ('FURGON', 'Furgón'), ('CAMION_PEQUEÑO', 'Camión Pequeño'), ('CAMION_GRANDE', 'Camión Grande'), ('MOTO', 'Motocicleta')], help_text='Tipo de vehículo (Ej: Camión, Furgón).', max_length=20, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.AddField(
            model_name='pedidos',
            name='conductor',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'CONDUCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='minorista',
            field=models.ForeignKey(limit_choices_to={'tipo': 'MINORISTA'}, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='envios',
            name='conductor',
            field=models.ForeignKey(limit_choices_to={'tipo': 'CONDUCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresas',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FRONTEND.pedidos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FRONTEND.productos')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Pedidos',
                'unique_together': {('pedido', 'producto')},
            },
        ),
        migrations.CreateModel(
            name='Asignaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FRONTEND.pedidos')),
                ('conductor', models.ForeignKey(limit_choices_to={'tipo': 'CONDUCTOR'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Asignaciones',
                'unique_together': {('pedido', 'conductor')},
            },
        ),
    ]
