# Generated by Django 5.2.8 on 2025-11-18 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MINORISTA', 'Minorista (Necesito hacer envíos)'), ('TRANSPORTISTA', 'Transportista (Ofrezco servicios de carga)'), ('ADMIN', 'Administrador de Cuenta')], default='MINORISTA', max_length=20, verbose_name='Rol del Usuario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
