# Generated by Django 5.2.8 on 2025-11-18 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRONTEND', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='role',
            field=models.CharField(choices=[('MINORISTA', 'Minorista (Necesito hacer envíos)'), ('CONDUCTOR', 'Transportista (Ofrezco servicios de carga)'), ('ADMIN', 'Administrador de Cuenta')], default='MINORISTA', max_length=20, verbose_name='Rol del Usuario'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfilusuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
