# Generated by Django 5.2.8 on 2025-12-01 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FRONTEND', '0002_alter_perfilusuario_role_alter_perfilusuario_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuario'},
        ),
    ]
