"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-s2wruh*ei*eh@d7581jvvyxqw_zgx)%v(ftcho6nl6e$$w+5bd'

DEBUG = True
ALLOWED_HOSTS = ['*'] # Correcto para desarrollo

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    
    'BACKEND',
    'FRONTEND',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

# 🚨 CONFIGURACIÓN DE PLANTILLAS CORREGIDA 🚨
# Se habilita 'APP_DIRS' para que busque en FRONTEND/templates/FRONTEND/...
# y DIRS para que también busque en una carpeta global 'templates/' si existe.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Ruta global para plantillas compartidas
        'APP_DIRS': True, # <--- CAMBIO CLAVE: Activado. Busca en las carpetas templates/ de cada APP.
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug', 
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'BOGOCARGOBASEDEDATOS',
        'USER': 'root', 
        'PASSWORD': 'sena', 
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES', character_set_connection=utf8mb4",
            'charset': 'utf8mb4',
        }
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'es-es'
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_TZ = True


# Static files
STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =================================================================
# CONFIGURACIÓN DE AUTENTICACIÓN
# =================================================================

AUTH_USER_MODEL = 'BACKEND.Usuarios'
LOGIN_URL = '/mi-cuenta/' 
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

AUTHENTICATION_BACKENDS = [
    'BACKEND.backends.EmailAuthBackend', 
    'django.contrib.auth.backends.ModelBackend',
]


# =================================================================
# CONFIGURACIÓN DE CORREO ELECTRÓNICO (EMAIL)
# =================================================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' 
EMAIL_HOST = 'smtp.gmail.com' 
EMAIL_PORT = 587 
EMAIL_USE_TLS = True 

# ⚠️ REEMPLAZA estos valores con tus credenciales reales ⚠️
EMAIL_HOST_USER = 'tucorreo_de_envio@gmail.com' 
EMAIL_HOST_PASSWORD = 'tu_contraseña_de_aplicacion' 

DEFAULT_FROM_EMAIL = 'BOGOCARGO <tucorreo_de_envio@gmail.com>'
